version: "2"
services:
  web:
    build: .
    environment:
      - DB_URL="mongodb://localhost:27017/shopping-list"
      - PORT=8080
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"