apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  # ports:
  #   - name: tcp
  #     port: 27017
  # type: ClusterIP
  # ports:
  #   - port: 27017
  #     nodePort: 27017
  